["protostar.config"]
protostar_version = "0.3.2"

["protostar.project"]
libs_path = "./lib/"

["protostar.shared_command_configs"]
cairo_path = ["./src"]
disable_hint_validation = true

[profile.devnet.protostar.deploy]
gateway-url="http://127.0.0.1:5050/"

[profile.testnet.protostar.deploy]
network="alpha-goerli"

[profile.mainnet.protostar.deploy]
network="alpha-mainnet"

["protostar.contracts"]
facilities = [
    "src/facilities/Facilities.cairo"
]
main = [
    "src/main/NoGame.cairo"
]
manager = [
    "src/manager/ModulesManager.cairo"
]
minter = [
   "src/minter/erc721_minter.cairo"
]
research = [
    "src/research/ResearchLab.cairo"
]
resources = [
    "src/resources/Resources.cairo"
]
shipyard = [
    "src/shipyard/Shipyard.cairo"
]
defences = [
    "src/defences/library.cairo"
]
erc20 = [
    "src/token/erc20/ERC20_Mintable_Burnable.cairo"
]
erc721 = [
    "src/token/erc721/ERC721.cairo"
]

