name: Tests

on:
  push:
    branches:
      - main

jobs:
  protostar:
    name: Protostar
    runs-on: ubuntu-latest
    steps:
      - name: Print working dir
        run: cd ..
      - name: Print working dir
        run: pwd
      - name: list files
        run: ls
      - name: Install Protostar
        uses: sambarnes/protostar-toolchain@main
      - name: Runs all the tests
        run: protostar test
